### ISSUE TITLE
Reconsider T: Drop

### ISSUE THREAD

**Issue by bluss** [burdges/zerodrop-rs#7]
`Drop` is not your usual trait. What does your bound do? It's probably not doing something sensible.

The `Drop` trait is used to hang destructors on types. Other types can have destructors without implementing Drop.

For example: `String` doesn't implement Drop, but it has a (structural) destructor that drops its fields (the Vec inside).

Another famous type that doesn't implement `Drop` is `Box<T>`...

**Comment by burdges** [comment]
Interesting.  I wrote `ZeroDropDrop` mostly as an exercise.  In fact, I've no tests for `ZeroDropDrop` because I cannot currently imagine any use cases.  If you want say a `Vec` to zero on drop, then you need either an allocator or a special data structure like [cryptovec](https://crates.io/crates/cryptovec) via https://github.com/burdges/zerodrop-rs/issues/5   Anyways this sounds like enough reason to comment it out and put a warning.  Thanks!
